FROM python:3.10

ENV APP_HOME=/home/app/api
WORKDIR $APP_HOME
COPY . $APP_HOME

RUN pip install -r requirements-dev.txt \
  && pip install -e .

#RUN groupadd app && useradd -g app app \
#  && pip install -r requirements-dev.txt \
#  && pip install -e . \
#  && chown -R app:app $APP_HOME
#
#USER app

CMD ["uvicorn", "pamps.app:app", "--host=0.0.0.0", "--port=8000", "--reload"]

